name: Update Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_message: "Update AI metrics"
          filename: .github/metrics.svg
          user: ghelanikirtan
          base: header, activity, repositories
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 500
          config_order: base.header, isocalendar, languages, achievements
